---
repos:
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
            args: [--quiet]
            exclude: node_modules

    - repo: local
      hooks:
          - id: prettier
            name: prettier
            entry: yarn prettier:fix
            language: system
            files: arches/app/src
