linters:
  black:
    config: ./pyproject.toml
    fixer: false
  eslint:
    config: './.eslintrc.js'
files:
  ignore:
    - 'arches/app/media/packages/*'
    - 'node_modules/*'
fixers:
  enable: false
