linters:
  pep8:
    python: 3
    ignore: 'W503'
    max-line-length: 140
    fixer: false
  black:
    config: ./pyproject.toml
    fixer: false
  eslint:
    config: './.eslintrc.js'
files:
  ignore:
    - 'arches/app/media/packages/*'
    - 'node_modules/*'
review:
  fail_on_comments: true
fixers:
  enable: false
