version: '2'
services:

    arches:
      container_name: arches
      image: arches/arches:latest
      build:
        context: .
        dockerfile: ./Dockerfile
      command: run_tests run_arches
      volumes:
        - arches-log:/arches/arches/logs
        - arches-static:/static_root
        - arches-bowercomponents:/web_root/arches/arches/app/media/bower_components
      environment:
        - FORCE_DB_INIT=False
        - INSTALL_DEFAULT_GRAPHS=True
        - INSTALL_DEFAULT_CONCEPTS=True
        - PGPASSWORD=postgres
        - PGDBNAME=arches
        - PGHOST=db
        - PGPORT=5432
        - ESHOST=elasticsearch
        - ESPORT=9200
        - DJANGO_MODE=DEV
        - DJANGO_DEBUG=True
        - DJANGO_NORELOAD=False
        - DOMAIN_NAMES=localhost
        - TZ=EST
      ports:
        - '8000:8000'
      depends_on:
        - db
        - elasticsearch

    db:
      container_name: db
      image: mdillon/postgis:9.6
      volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - TZ=EST

    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:5.2
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - TZ=EST


volumes:
    arches-log:
    arches-static:
    arches-bowercomponents:
    postgres-data:
    postgres-log:
    elasticsearch-data:
    elasticsearch-config:
